spring:
    application:
        name: UserApi
    datasource:
        url: ${MYSQL_URL:jdbc:mysql://localhost:3306/microServicesUser}
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:0123}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    port: ${PORT:8000}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}